version: "3.8"
services:
  of-scraper:
    stdin_open: true # Keeps STDIN open for interactive processes
    tty: true # Allocates a pseudo-TTY for a terminal-like interface
    container_name: ofscraper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OF_API_KEY=${OF_API_KEY}
      - OF_DOWNLOAD_PATH=${OF_DOWNLOAD_PATH}
    volumes:
      # Mount your configuration directory (replace ./config/ with your host path)
      - ./config/:/home/ofscraper/.config/ofscraper/
      # Mount your data storage directory (replace ./data/ with your host path)
      - ./data/:/app/data/
    ports:
      - "5001:5000"
    command: ["/bin/bash", "-c", "sleep infinity"]
