name: Build and Package

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

permissions: read-all

jobs:
  generate_version:
    name: Generate Version Info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      sanitized_version: ${{ steps.version.outputs.SANITIZED_VERSION }}
      short_hash: ${{ steps.version.outputs.SHORT_HASH }}
      long_hash: ${{ steps.version.outputs.LONG_HASH }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Make script executable
        run: chmod +x ./scripts/commit_version.sh
      - name: Generate Version from Git
        id: version
        run: ./scripts/commit_version.sh

  build_binaries:
    name: Build on ${{ matrix.os }}
    needs: [generate_version]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_suffix: linux
            shell: bash
          - os: windows-latest
            artifact_suffix: windows
            shell: pwsh
          - os: macos-latest
            artifact_suffix: macos
            shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'
      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set Version Environment Variables
        shell: bash
        run: |
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=${{ needs.generate_version.outputs.version }}" >> $GITHUB_ENV
          echo "HATCH_VCS_PRETEND_VERSION=${{ needs.generate_version.outputs.version }}" >> $GITHUB_ENV

      - name: Install Dependencies and Build Tools
        shell: bash
        run: |
          uv venv
          if [ "${{ runner.os }}" == "Windows" ]; then
            . .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          # Install core, ffmpeg, and dev dependencies all at once from pyproject.toml
          uv sync --verbose --extra ffmpeg --extra dev

      - name: Set UTF-8 environment (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "PYTHONUTF8=1" >> $env:GITHUB_ENV
          echo "PYTHONLEGACYWINDOWSSTDIO=utf8" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build Executable using Spec Files
        shell: bash
        run: |
          SANITIZED_VERSION="${{ needs.generate_version.outputs.sanitized_version }}"
          EXE_NAME="ofscraper_${{ matrix.artifact_suffix }}_${SANITIZED_VERSION}"
          DIR_NAME="ofscraper_${{ matrix.artifact_suffix }}_dir"
          
          # Activate venv
          if [ "${{ runner.os }}" == "Windows" ]; then
              source .venv/Scripts/activate
              EXE_EXT=".exe"
          else
              source .venv/bin/activate
              EXE_EXT=""
          fi
          
          # --- CHANGE: Point to the spec files in the 'specs/' directory ---
          echo "Building one-file executable from specs/onefile.spec..."
          pyinstaller specs/onefile.spec
          mv dist/ofscraper${EXE_EXT} dist/${EXE_NAME}${EXE_EXT}

          # --- CHANGE: Point to the spec files in the 'specs/' directory ---
          echo "Building one-dir bundle from specs/onedir.spec..."
          pyinstaller specs/onedir.spec
          mv dist/ofscraper dist/${DIR_NAME}

          # Zip the one-dir build
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell -Command "Compress-Archive -Path dist/${DIR_NAME} -DestinationPath dist/ofscraper_${{ matrix.artifact_suffix }}_${SANITIZED_VERSION}.zip -Force"
          else
            zip -r "dist/ofscraper_${{ matrix.artifact_suffix }}_${SANITIZED_VERSION}.zip" "dist/${DIR_NAME}"
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.artifact_suffix }}
          path: |
            dist/*.exe
            dist/*.zip
            dist/ofscraper_${{ matrix.artifact_suffix }}_${{ needs.generate_version.outputs.sanitized_version }}
          if-no-files-found: ignore

  publish_release:
    name: Publish GitHub Release
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')
    needs: [build_binaries, generate_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: List downloaded files for debugging
        run: ls -R artifacts

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/*/*
          tag: "dev-${{ needs.generate_version.outputs.short_hash }}"
          name: "Dev Build ${{ needs.generate_version.outputs.short_hash }}"
          body: "This is an auto-generated development release created from commit hash `${{ needs.generate_version.outputs.long_hash }}`. Version: `${{ needs.generate_version.outputs.version }}`"
          commit: "${{ needs.generate_version.outputs.long_hash }}"
          allowUpdates: true
          prerelease: true