publish_release:
    name: Publish GitHub Release
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')
    needs: [build_binaries, generate_version]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: List downloaded files for debugging
        run: ls -R artifacts

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/*/*
          # Combine base version, short hash, and commit timestamp for the tag
          tag: "dev-${{ needs.generate_version.outputs.base_version }}-${{ needs.generate_version.outputs.short_hash }}-${{ needs.generate_version.outputs.commit_timestamp }}"
          # Something similar with spaces for the name (more human-readable)
          name: "Dev Build ${{ needs.generate_version.outputs.base_version }} (Commit ${{ needs.generate_version.outputs.short_hash }}) - ${{ needs.generate_version.outputs.commit_timestamp }}"
          
          body: "This is an auto-generated development release created from commit hash `${{ needs.generate_version.outputs.long_hash }}`. Version: `${{ needs.generate_version.outputs.version }}`"
          commit: "${{ needs.generate_version.outputs.long_hash }}"
          allowUpdates: true
          prerelease: true